services:
  proxy:
    image: ${DOCKER_IMAGE}
    container_name: proxy
    environment:
      - INSTANCE_GCP=${INSTANCE_GCP}
    volumes:
      - ./credential.json:/app/credential.json:ro
    ports:
      - "3307:3307"
    entrypoint: ["/app/entrypoint_proxy.sh"]